### ISSUE TITLE
Segment error

### ISSUE THREAD

**Issue by hanqingwu** [xindawndev/xindawn-linux-airplay-mirroring-sdk-ubuntu-x86_64#3]
I make and start in  4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux .  
then  i use ipad 10.3.5 (IOS)  found XBMC-GAMEBOX , but when i  choose to connect  it . This  app crash !

airmirrorserver[14162]: segfault at 7f64c26b2040 ip 000000000048b2e8 sp 00007f64e6543570 error 4 in airmirrorserver[400000+aae000]

**Comment by xindawndev** [comment]
Please update to the latest version.

2017-06-20 14:45 GMT+08:00 hanqingwu <notifications@github.com>:

**Comment by hanqingwu** [comment]
Thanks , it works well!
